apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: paulbouwer/hello-kubernetes:1.10.1
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "1"]
