apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    last-update: 1727102560
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test-container
        image: bash
        command:
        - sleep
        args:
        - "30"
