apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    last-update: foo
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test-container
        image: bash
        command:
        - sleep
        args:
        - "100"
